name: ahakam_v8
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.3.0
dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  cloud_firestore: ^5.6.7
  get: ^4.7.2
  intl: ^0.20.2
  firebase_auth: ^5.5.3
  firebase_core: 3.13.0
  google_fonts: ^6.2.1
  flutter_image_compress: ^2.4.0
  lucide_icons: ^0.257.0
  fl_chart: ^0.71.0
  flutter_rating_bar: ^4.0.1
  supabase_flutter: ^2.9.0
  image_picker: ^1.1.2
  shimmer: ^3.0.0
  liquid_pull_to_refresh: ^3.0.1
  url_launcher: ^6.2.5
  font_awesome_flutter: ^10.8.0
  flutter_animate: ^4.2.0
  table_calendar: ^3.0.9
  dropdown_button2: ^2.3.9
  flutter_stripe: ^11.5.0
  http: ^1.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0


flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/criminal.png
    - assets/images/commercial.png
    - assets/images/insurance.png
    - assets/images/international.png
    - assets/images/labor.png
    - assets/images/civil.png
    - assets/images/ehkaam-seeklogo.png

  
